/* eslint-disable max-len */
// Datenbasis (aus deiner Nachricht übernommen). Jede Regel wird als einzelne Frage abgefragt.
// Frageformat: "Welche Sanktion/Strafe ist für diese Regel angegeben?"
//
// Hinweis: Wenn keine Strafe im Regeltext stand, ist die korrekte Antwort "Keine Angabe".

window.RULES_DATA = [
  // Allgemeine Regeln → Accountinhaber
  {
    section: "Allgemein · Account",
    id: "1.1",
    text: "Der erstellte Account ist Eigentum des Erstellers. Der Account darf nicht geteilt oder verkauft werden.",
    penalty: "Permanenter Bann",
  },
  {
    section: "Allgemein · Account",
    id: "1.2",
    text: "Der Inhaber ist für sein Account voll verantwortlich. Die Administration trägt keine Verantwortung für dein Account. Wenn der Zugang zum Account verloren geht (z. B. durch Hacking), wird dein Account mit denselben Strafen belangt.",
    penalty: "Keine Angabe",
  },
  {
    section: "Allgemein · Account",
    id: "1.3",
    text: "Jeder Betrug gegenüber anderen Spielern ist verboten.",
    penalty: "Permanenter Bann - Es wird kein Geld ersetzt",
  },
  {
    section: "Allgemein · Account",
    id: "1.4",
    text: "Es ist verboten, mehr als ein zusätzlichen Account zu haben (Twinking).",
    penalty: "Permanenter Bann für alle zusätzlichen Konten | Hauptaccount Bann 60 Tage",
  },
  {
    section: "Allgemein · Account",
    id: "1.5",
    text: "Es ist verboten, mehr als 1 Business zu besitzen. 1 Person - 1 Business (Familienbusiness ausgeschlossen).",
    penalty: "Bann 30 Tage",
  },
  {
    section: "Allgemein · Account",
    id: "1.6",
    text: "Der Versuch, Spieleigentum für Echtgeld/Grandcoins zu verkaufen/kaufen ist verboten.",
    penalty: "Permanenter Bann",
  },
  {
    section: "Allgemein · Account",
    id: "1.7",
    text: "Es ist verboten, Eigentum als Geschenk zu übertragen (einschließlich Neon-Schuhe), dessen Gesamtbetrag 5.000.000$ übersteigt (Sie dürfen 5.000.000$ erhalten und 5.000.000$ pro Tag überweisen.) (Es ist erlaubt, Geld vom/auf das Familienguthaben abzuheben/einzuzahlen.)",
    penalty: "Ban 60 Tage",
  },
  {
    section: "Allgemein · Account",
    id: "1.8",
    text: "Es ist verboten, zwischen dem Hauptaccount und dem Twink zu interagieren.",
    penalty: "Permanente Sperre beider Accounts",
  },
  {
    section: "Allgemein · Account",
    id: "1.9",
    text: "Es ist verboten, die Systeme für den Verkauf/Kauf zu umgehen um Steuern zu sparen (Verkauf/Kauf/Handel von Häusern/Gegenständen/Autos/Kleidung für 1k und dann Geld so bekommen).",
    penalty: "Bann 60 Tage",
  },

  // Nicknamen-Erstellung
  {
    section: "Allgemein · Nickname",
    id: "2.1",
    text: "Die Ingamenamen müssen realistische Namen sein. Der Name muss sich auf die reale Welt beziehen und Namen berühmter Personen/beleidigen/Anspielung dürfen nicht verwendet werden (z. B. Max Mustermann).",
    penalty: "Jail 10 Minuten und Name ändern",
  },

  // Kommunikationsregeln
  {
    section: "Allgemein · Kommunikation",
    id: "3.1",
    text: "OOC Beleidigungen sind untersagt.",
    penalty: "Mute 180 Minuten / Bann 1-7 Tage",
    explanation:
      "Alles, was du außerhalb deines Charakters sagst (OOC), muss respektvoll bleiben. Beleidigungen im OOC eskalieren Situationen und sind daher verboten.",
    exampleGood: "Du klärst Streit IC oder meldest es per Report/Forum – ohne OOC zu beleidigen.",
    exampleBad: "Du schreibst/ sagst im OOC-Chat: „Du bist …“ oder beleidigst im Discord wegen einer IC-Situation.",
  },
  { section: "Allgemein · Kommunikation", id: "3.2", text: "Jegliche Verwandte dürfen in keinerlei Chats/Voice oä. erwähnt werden.", penalty: "Mute 180 Minuten / Bann 1-7 Tage" },
  { section: "Allgemein · Kommunikation", id: "3.3", text: "Alle Spieler müssen Deutsch reden. Andere Sprachen dürfen nur in kleinen Kreisen verwendet werden.", penalty: "Mute 120 Minuten" },

  // Hacking und externe Software
  { section: "Allgemein · Software", id: "4.1", text: "Spieler dürfen keine externe Software benutzen, die einem einen Vorteil verschaffen (Hacks, Bots usw.).", penalty: "Bann 60 Tage - Bis permanenter Bann" },

  // Umgang mit der Administration
  { section: "Allgemein · Administration", id: "5.1", text: "Es ist verboten, den Ingame-Report für Fragen zu verwenden, die nichts mit dem Spiel zu tun haben.", penalty: "Mute 20-60 Minuten" },
  { section: "Allgemein · Administration", id: "5.2", text: "Alle Spieler müssen den Anweisungen der Administration Folge leisten. Bei extremen Unstimmigkeiten, kann eine Beschwerde gegen den Administration im Forum eingelegt werden.", penalty: "Keine Angabe" },
  { section: "Allgemein · Administration", id: "5.3", text: "Beleidigungen an die Administration sind verboten. Sollte ein Administrator beleidigen, kann dies im Forum gemeldet werden.", penalty: "Bann 7 Tage" },

  // Regeln des Spiels
  { section: "Spielregeln", id: "6.1", text: "Die falsche Verwendung der Befehle /me /do /try /todo ist verboten. Der Spieler ist verpflichtet, die Befehle richtig zu benutzen.", penalty: "Keine Angabe" },
  {
    section: "Spielregeln",
    id: "6.2",
    text: "Es ist verboten, RP-Situationen zu verlassen, indem du AFK gehst, einen Innenraum betrittst, welcher von anderen Spielern nicht betreten werden kann o.ä.",
    penalty: "Warn",
    explanation:
      "Wenn du in einer aktiven RP-Situation bist, musst du die Situation IC zu Ende spielen. AFK gehen oder in unzugängliche Interiors flüchten zählt als „Situation verlassen“.",
    exampleGood: "Du spielst die Situation aus (z.B. ergeben/reden/flüchten IC) und gehst erst danach AFK.",
    exampleBad: "Du wirst gestellt und gehst plötzlich AFK oder verschwindest in ein Interior, dem andere nicht folgen können.",
  },
  { section: "Spielregeln", id: "6.3", text: "Es ist verboten, das Lager von Familien/Organisationen für persönliche Zwecke zu leeren.", penalty: "Permanenter Bann" },
  { section: "Spielregeln", id: "6.4", text: "Es ist verboten, einen Bad-Angestellten der staatlichen Organisationen zu spielen, ohne eine RP-Biographie zu haben.", penalty: "Warn" },
  { section: "Spielregeln", id: "6.5", text: "Es ist verboten, kriminelle Handlungen gegen EMS-Mitarbeitern zu begehen (töten, ausrauben usw.).", penalty: "Warn" },
  { section: "Spielregeln", id: "6.6", text: "Es ist verboten, sich in einer Schießerei zu heilen oder zu looten.", penalty: "Jail 60 Minuten" },
  { section: "Spielregeln", id: "6.7", text: "Wenn du getötet wurdest (und im Krankenhaus spawnst), darfst du 15 Minuten lang nicht mehr in den Kampf zurückkehren.", penalty: "Warn" },
  { section: "Spielregeln", id: "6.8", text: "Es ist verboten, nichtypische Handlungen im Bezug auf eine bewusstlose Person durchzuführen (z.B. Spucken, sexuelle Animationen usw.).", penalty: "Bann 3-7 Tage" },
  { section: "Spielregeln", id: "6.9", text: "Es ist verboten, sexuelle Handlungen an einer Person vorzunehmen. Wenn du Opfer einer sexuellen Belästigung (RP-Vergewaltigung) wirst, hast du die Erlaubnis von dort zu flüchten.", penalty: "Bann 3-7 Tage" },
  {
    section: "Spielregeln",
    id: "6.10",
    text: "Es ist verboten, IC-Situationen in den OOC-Bereich zu verlagern (z.B. jemanden in Discord-Chats in Bezug auf eine IC-Situation zu beleidigen).",
    penalty: "Bann 1-7 Tage",
    note: "Zusätzlich kann es eine Discord-Strafe geben.",
    explanation:
      "Konflikte aus dem Roleplay bleiben im Roleplay. OOC/Discord als „Nachtreten“ oder zum Beleidigen/Anprangern wegen einer IC-Situation ist nicht erlaubt.",
    exampleGood: "Du regelst es IC oder meldest Regelbrüche sachlich (Report/Forum) – ohne OOC-Streit.",
    exampleBad: "Du beleidigst jemanden im Discord, weil er dich IC festgenommen/ausgeraubt hat.",
  },
  { section: "Spielregeln", id: "6.11", text: "Es ist verboten, mit einem Twink-Account für die andere Seite zu spielen (Haupt legal → Twink legal; Haupt illegal → Twink illegal).", penalty: "Warn für beide Accounts" },
  { section: "Spielregeln", id: "6.12", text: "Das Belästigen von EMS-Mitarbeitern im Dienst oder das unangemessene Verhalten gegenüber EMS-Mitarbeitern ist verboten. Ausnahme: Der EMS-Mitarbeiter war respektlos.", penalty: "Bann 1-7 Tage" },
  { section: "Spielregeln", id: "6.13", text: "Es ist verboten, eine Person zu töten, die bewusstlos ist, um ihr zu helfen, eine RP-Situation zu vermeiden (Mercy Killing).", penalty: "Jail 120 Minuten | Warn" },
  { section: "Spielregeln", id: "6.14", text: "Es ist nur erlaubt, Munition, Waffen, jegliche Westen, Balaclava und Drogen von anderen Spielern zu klauen. Geld darf nur über die Systemfunktion von Gangs gestohlen werden.", penalty: "Bann 1-7 Tage" },
  { section: "Spielregeln", id: "6.15", text: "Außerhalb des Ghettos/Stadt musst du dich auf das RP einlassen, bevor du jemanden erschießt (z.B. Forderungen; nach 5 Sekunden ohne Reaktion).", penalty: "Warn" },
  { section: "Spielregeln", id: "6.16", text: "Bei einem Überfall auf eine Person/ein Fahrzeug müssen mindestens 2 Autos (gleiche Farbe) und 4 Personen beteiligt sein. Wenn das Auto nicht anhält, wird es als “Power Gaming” betrachtet.", penalty: "Jail 120 Minuten | Warn" },
  { section: "Spielregeln", id: "6.17", text: "Gelöschte Regel.", penalty: "Keine Angabe", deleted: true },
  { section: "Spielregeln", id: "6.18", text: "Es ist verboten, Helikopter zu benutzen um auf Dächer zu gelangen, die nicht zu Fuß oder über eine Leiter erreicht werden können.", penalty: "Jail 120 Minuten" },
  { section: "Spielregeln", id: "6.19", text: "H-Wort und N-Wort sind verboten.", penalty: "Bann 1-3 Tage" },
  { section: "Spielregeln", id: "6.20", text: "Das Muten von anderen Spielern, was zur Vermeidung von RP führt, entbindet nicht von einer Bestrafung und fällt unter Fail RP.", penalty: "Warn" },
  { section: "Spielregeln", id: "6.21", text: "Es ist verboten, gepanzerte Fahrzeuge zu benutzen, um geschützt vor Schüssen zu sein.", penalty: "Warn" },
  { section: "Spielregeln", id: "6.22", text: "Es ist verboten, Familienunternehmen zu verkaufen/kaufen oder Geld vom/auf Familienkonto abzuheben/einzuzahlen ohne Zustimmung des Familien Leaders, sowie aus Lager/Familienautos Gegenstände zu nehmen.", penalty: "Fällt unter 1.3" },
  { section: "Spielregeln", id: "6.23", text: "Jegliche Art von Bugabuse sind verboten.", penalty: "Bann 60 Tage - Permanenter Bann" },
  { section: "Spielregeln", id: "6.24", text: "Es ist verboten, Personen auszurauben oder zu kidnappen, welche Anfangsjobs (Busfahrer/Taxi-Fahrer/Elektriker etc.) ausüben.", penalty: "Warn" },
  { section: "Spielregeln", id: "6.25", text: "Es ist verboten, Menschen auf dem Gebiet von Fort Zancudo (Nationalgarde) auszurauben/zu entführen.", penalty: "Warn" },
  { section: "Spielregeln", id: "6.26", text: "Es ist verboten, EMS-Kleidung zu missbrauchen, wenn man kein EMS-Mitarbeiter ist.", penalty: "Warn oder Bann bis zu 7 Tagen" },
  { section: "Spielregeln", id: "6.27", text: "Es ist nicht gestattet, die Schmuggelmaschine (Hauptmodul) in anderen Gegenständen oder an physisch unzugänglichen Orten zu verstecken.", penalty: "Bann 1–3 Tage" },
  { section: "Spielregeln", id: "7.1", text: "Gelöschte Regel.", penalty: "Keine Angabe", deleted: true },
  { section: "Spielregeln", id: "7.2", text: "Das vermehrte Verstoßen gegen die gleichen Regeln führt zu härteren Sanktionen.", penalty: "Bann 1-30 Tage" },
  { section: "Spielregeln", id: "7.3", text: "Das Spielen eines weiblichen Spielers als männliche Person ist nur mit einer Biografie erlaubt.", penalty: "Jail 60 Minuten + Geschlechtsänderung" },

  // Roleplay-Begriffe und Regeln
  { section: "RP Begriffe", id: "1.1", text: "In Charakter (IC): Das ist das Roleplay deines Charakters. Deine Handlungen und deine Worte.", penalty: "Keine Angabe" },
  { section: "RP Begriffe", id: "1.2", text: "Out of Character (OOC): Wenn du ausserhalb deiner Person sprichst, die nichts mit dem Roleplay zu tun hat.", penalty: "Keine Angabe" },
  {
    section: "RP Begriffe",
    id: "1.3",
    text: "Metagaming (MG): Informationen ausserhalb des Spiels bekommen und im Spiel verwenden; auch MG anstiften ist verboten.",
    penalty: "Mute 60-180 Minuten | Jail 60-180 Minuten",
    explanation:
      "Du darfst OOC-Infos (Discord/Stream/2. Monitor/anderer Spieler OOC) nicht nutzen, um IC Vorteile zu haben. IC brauchst du eine Ingame-Info/Begründung.",
    exampleGood: "Du erfährst IC über Funk/Telefon/Beobachtung, wo jemand ist, und reagierst darauf.",
    exampleBad: "Ein Freund schreibt dir im Discord „ich werde dort überfallen“ und du fährst direkt hin, ohne IC etwas zu wissen.",
  },
  {
    section: "RP Begriffe",
    id: "1.4",
    text: "Powergaming (PG): Nicht menschenähnliche Situationen; anderen RP aufzwingen; Dinge erfinden; RP skripttechnisch unmöglich, etc.",
    penalty: "Jail 120-180 Minuten",
    explanation:
      "Du darfst niemandem unfair die Handlung wegnehmen oder Dinge „festschreiben“, ohne dem anderen eine Chance zu geben zu reagieren. Auch unrealistische/skript-unmögliche Aktionen zählen dazu.",
    exampleGood: "Du stellst eine Forderung und gibst dem Gegenüber realistisch Zeit zu reagieren.",
    exampleBad: "„/me schlägt dich sofort KO und fesselt dich“ ohne Gegenchance oder mit unmöglichen Aktionen.",
  },
  {
    section: "RP Begriffe",
    id: "1.5",
    text: "Deathmatch (DM): Töten ohne ausreichenden RP-Grund ist nicht erlaubt.",
    penalty: "Jail 120-180 Minuten oder Warn",
    explanation:
      "Töten braucht einen nachvollziehbaren RP-Grund und meist eine vorherige RP-Interaktion. Einfach so schießen, weil es „passt“, ist DM.",
    exampleGood: "Du hast eine eskalierte Situation mit klarer Vorgeschichte und spielst sie aus.",
    exampleBad: "Du schießt random auf jemanden ohne Gespräch/Forderung/Grund.",
  },
  { section: "RP Begriffe", id: "1.6", text: "UN-RP: In einer Situation Dinge tun, die nicht angemessen sind (trollen, tanzen, schreien, Angst nicht ausspielen, etc.).", penalty: "Jail 120-180 Minuten oder Warn" },
  { section: "RP Begriffe", id: "1.7", text: "Revenge Killing (RK): Nach Tod und Krankenhaus nicht zur Situation zurückkehren, um die Person zu töten.", penalty: "Jail 120 Minuten" },
  { section: "RP Begriffe", id: "1.8", text: "Car Ramming: Fahrzeug nutzen um mit Fahrzeugen oder Personen zu kollidieren ist verboten.", penalty: "Jail 120-180 Minuten oder Warn" },
  { section: "RP Begriffe", id: "1.9", text: "Baiting: Absichtlich nervig/irritierend sein, um Reaktionen zu bekommen.", penalty: "Jail 120-180 Minuten" },
  { section: "RP Begriffe", id: "1.10", text: "Unrealistisches Verhalten (UB): Unrealistische Aktionen, die RP-Erfahrung anderer verletzen (als UN-RP betrachtet).", penalty: "Jail 120 Minuten" },
  {
    section: "RP Begriffe",
    id: "1.11",
    text: "Fail-RP: In aktiver RP-Situation aufs Regelwerk anspielen/OOC reden; Wiederbelebung nicht akzeptieren, Erste-Hilfe verweigern, Combat logging etc.",
    penalty: "Warn",
    explanation:
      "In einer laufenden RP-Situation bleibst du IC und spielst realistisch mit. Alles, was die Situation „kaputt macht“ (OOC talk, bewusstes Verhindern von RP, Combat-Logging), fällt darunter.",
    exampleGood: "Du akzeptierst die RP-Entwicklung (z.B. Behandlung/Wiederbelebung) und klärst Regelbruch später per Report.",
    exampleBad: "Du redest mitten im RP über Regeln oder loggst aus, um einer Situation zu entgehen (Combat logging).",
  },

  // Leader-Regeln
  {
    section: "Leader Regeln",
    id: "1.1",
    text: "Leader müssen mindestens 30 Tage Leader sein, andernfalls wird der Leader von seinem Posten entfernt und das Konto 3 Tage gesperrt. Wenn der Leader seinen Posten aus schwerwiegenden Gründen verlässt, wird er ohne Bann entfernt und sein Posten wird an einen vertrauenswürdigen Co-Leader übertragen oder es wird ein neuer Leader gesucht.",
    penalty: "Kontosperre 3 Tage (bei <30 Tagen)",
  },
  { section: "Leader Regeln", id: "1.2", text: "Es ist verboten, das Lager der Organisation für persönliche Zwecke zu nutzen.", penalty: "Keine Angabe" },
  { section: "Leader Regeln", id: "1.3", text: "Wenn der Leader gewechselt wird, hat er das Recht, die Organisation für 24 Stunden einzufrieren (Aufbau-Schutz).", penalty: "Keine Angabe" },
  { section: "Leader Regeln", id: "1.4", text: "Der Leader von einer Gang hat das Recht auf 4 Co-Leader.", penalty: "Keine Angabe" },
  { section: "Leader Regeln", id: "1.5", text: "Der Leader von staatlichen Organisationen (+ Lifeinvader) hat das Recht auf 2 Co-Leader.", penalty: "Keine Angabe" },
  { section: "Leader Regeln", id: "1.6", text: "Der Leader einer Organisation hat den Rang 10.", penalty: "Keine Angabe" },
  { section: "Leader Regeln", id: "1.7", text: "Der Leader der Organisation hat das Recht, Mitarbeiter seiner Organisation zu entlassen, wenn er mit Zustimmung des Curators das Vertrauen in sie verloren hat.", penalty: "Keine Angabe" },
  { section: "Leader Regeln", id: "1.8", text: "Der Leader kann einmal pro Wahlperiode mit Genehmigung des Kurators eine Pause von 12-24 Stunden einlegen.", penalty: "Keine Angabe" },
  { section: "Leader Regeln", id: "1.9", text: "Jeder Leader muss mindestens einmal in 2 Wochen ein globales Ereignis veranstalten.", penalty: "Keine Angabe" },
  { section: "Leader Regeln", id: "1.10", text: "Die Leitung einer inoffiziellen Organisation darf nicht übertragen/Fusioniert/Verkauft oä. werden, der Status wird hierbei sofort entzogen.", penalty: "Status wird entzogen" },

  // Pflichten eines Leaders
  { section: "Leader Pflichten", id: "2.1", text: "Kenntnis des gesamten Regelwerks.", penalty: "Keine Angabe" },
  { section: "Leader Pflichten", id: "2.2", text: "Mindest-Onlinezeit von 2+ Stunden am Tag.", penalty: "Keine Angabe" },
  { section: "Leader Pflichten", id: "2.3", text: "Keine provokativen und konfliktreichen Situationen zwischen den Mitgliedern und der Organisationen.", penalty: "Keine Angabe" },
  { section: "Leader Pflichten", id: "2.4", text: "Den Anforderungen des Curators ist immer folge zu leisten und diese zu erfüllen.", penalty: "Keine Angabe" },

  // Verboten für Leader
  { section: "Leader Verbote", id: "3.1", text: "An anderen RP-/RPG-Projekten für GTA V und SAMP mitwirken und eine beliebige Position innehaben (Leader, Admin, Teilnahme am Discord eines anderen Servers usw.).", penalty: "Keine Angabe" },
  { section: "Leader Verbote", id: "3.2", text: "Wenn du mit deinem Twink-Account für die gleiche Organisation spielst, aber in einem anderen Bereich/Abteilung bist.", penalty: "Keine Angabe" },
  { section: "Leader Verbote", id: "3.3", text: "Toxisches und unangemessenes Verhalten gegenüber seiner und anderen Organisationen (Leitung) ist strikt untersagt.", penalty: "Keine Angabe" },

  // Event-Regeln
  { section: "Event Regeln", id: "1.1", text: "Teaming ist strengstens verboten (außer bei Events, bei denen es erlaubt ist). In Team- oder Familien-Events ist es verboten, seine eigenen Teammitglieder zu töten.", penalty: "Jail 120 Minuten" },
  { section: "Event Regeln", id: "1.2", text: "Es ist verboten, 10 Minuten vor Beginn, während und 5 Minuten nach des Events jemanden zu töten/auszurauben/kidnappen/etc.", penalty: "Warnung" },
  { section: "Event Regeln", id: "1.3", text: "Es ist verboten, den Gebietsbereich vor Beginn des Events zu betreten.", penalty: "Jail 120 Minuten" },
  { section: "Event Regeln", id: "1.4", text: "Das Limit von Überfällen auf Waffenläden und 24/7 sind 40/40 Personen.", penalty: "Jail 180 Minuten" },
  { section: "Event Regeln", id: "1.5", text: "Bei Überfällen auf Waffenläden und 24/7 muss ein Rollenspiel sein und die Beamten müssen mit den kriminellen reden.", penalty: "Jail 180 Minuten" },
  { section: "Event Regeln", id: "1.6", text: "Maschinengewehre und Scharfschützengewehre sind verboten.", penalty: "Jail 120 Minuten" },
  { section: "Event Regeln", id: "1.7", text: "Alle Mitglieder des Events müssen eine POV haben und 48 Stunden aufheben.", penalty: "Bann 30 Tage" },
  { section: "Event Regeln", id: "1.8", text: "Es ist verboten, Familienmitglieder zwischen Familien zu tauschen für Familienkriege.", penalty: "Warn" },
  { section: "Event Regeln", id: "1.9", text: "Es ist verboten, die Durchgänge mit Barrikaden oder Autos zu blockieren. Mindestens ein Durchgang muss frei sein, zum flüchten.", penalty: "Jail 120 Minuten" },
  { section: "Event Regeln", id: "1.10", text: "Während der Purge ist es verboten, Waffen auf den Familien-/Organisationslagern zu nehmen. Alle Lager müssen eine Stunde vor Purge Beginn geschlossen sein.", penalty: "Bann 30 Tage" },
  { section: "Event Regeln", id: "1.11", text: "Bei allen Events muss man sich im Gebiet aufhalten. Es darf nicht von außen geschossen werden.", penalty: "Jail 120 Minuten" },
  { section: "Event Regeln", id: "1.12", text: "Bei Überfall-Events und Entführungen gibt es ein Limit von 2 Geiseln.", penalty: "Warn" },
  { section: "Event Regeln", id: "1.13", text: "Familien dürfen bei Flugzeugträger-, Bankraub- und Gefängnis-Event keine anderen Familienmitglieder absichtlich töten.", penalty: "Jail 120 Minuten" },
  { section: "Event Regeln", id: "1.14", text: "Während des Überfalls auf das Fort Zancudo ist es verboten, Dächer zu besetzen.", penalty: "Jail 120 Minuten" },
  { section: "Event Regeln", id: "1.15", text: "Während des U-Boot-Events ist es verboten, Dächer zu besetzen.", penalty: "Jail 120 Minuten" },
  { section: "Event Regeln", id: "1.16", text: "Während einer Geiselnahme können die Familien für eine Geisel einen bestimmten Geldbetrag verlangen (nur 1 Forderung pro 1 Geisel).", penalty: "Keine Angabe" },
  { section: "Event Regeln", id: "1.17", text: "Es ist verboten private Fahrzeuge bei Events zu benutzen, während man als Gangmitglied agiert (man darf nur Gang-Autos nutzen).", penalty: "Keine Angabe" },
  { section: "Event Regeln", id: "1.18", text: "Nach Eventstart ist es verboten, Orte zu besuchen, die man nicht zu Fuß oder per Leiter innerhalb des Gebiets betreten kann. Ebenfalls ist es verboten, sich vor Beginn des Events auf einen Highground zu begeben, welchen man nach Start nicht mehr erreichen kann (Autobahn etc.).", penalty: "Jail 120 Minuten" },
  { section: "Event Regeln", id: "1.19", text: "Während eines Waffenladen- oder 24/7-Raubs ist es den FIB, SAHP, PD Beamten gestattet zu fordern die Geiseln durch Beamte oder ähnliche zu ersetzen.", penalty: "Keine Angabe" },
  { section: "Event Regeln", id: "1.20", text: "Beim Bankraub-Event ist es nicht erlaubt zu töten, anzugreifen, zu schießen oder auszurauben, während beim Spieler das Interieur noch lädt.", penalty: "WARN" },
  { section: "Event Regeln", id: "1.21", text: "Während des Flugzeugträger-Events dürfen Beamte nicht auf Personen schießen, während diese im Wasser sind. Sie müssen die Personen auf den Träger kommen lassen.", penalty: "Warn" },
  { section: "Event Regeln", id: "1.22", text: "Fallschirme sind verboten (Bug-Abuse). Bsp: Fliegen in die rote Zone mit einem Fallschirm.", penalty: "Bann 1-30 Tage" },

  // Ghetto-Regeln
  { section: "Ghetto Regeln", id: "1.1", text: "Die Ghetto Gebiete sind farblich auf der Karte markiert, je nachdem zu welcher Gang sie gehören.", penalty: "Keine Angabe" },
  { section: "Ghetto Regeln", id: "1.2", text: "Wenn du im HQ einer Gang bist, musst du alle Regeln der Gang befolgen.", penalty: "Warn" },
  { section: "Ghetto Regeln", id: "1.3", text: "Das betreten eines HQ’s ist ohne IC-Grund (z.B. Überfall, Gespräch mit dem Leader) für alle Organisationen verboten.", penalty: "Warn" },
  { section: "Ghetto Regeln", id: "1.4", text: "Es ist verboten, Gangmitglieder in ihrem HQ zu töten oder anzugreifen; das HQ darf nicht ohne Erlaubnis betreten werden.", penalty: "Warn" },
  { section: "Ghetto Regeln", id: "1.5", text: "Wenn du dich in deinem HQ befindest, ist es verboten aus dem HQ rauszuschießen.", penalty: "Warn" },
  { section: "Ghetto Regeln", id: "1.6", text: "Wenn ein Gangmitglied von Cops/Gangs gejagt wird, darf er erst 5 Minuten später ins HQ zurückkehren.", penalty: "Warn" },
  { section: "Ghetto Regeln", id: "1.7", text: "Alle Gangmitglieder müssen das Oberteil und die Hose in der jeweiligen Gangfarbe tragen.", penalty: "Jail 180 Minuten" },
  { section: "Ghetto Regeln", id: "1.8", text: "Ein Raub/Kidnapping ist nur im Ghetto oder außerhalb der Stadt erlaubt.", penalty: "Warn" },
  { section: "Ghetto Regeln", id: "1.9", text: "Raubüberfälle auf das Fort Zancudo sind nur von 12:00 Uhr bis 22:00 Uhr erlaubt.", penalty: "Keine Angabe" },
  { section: "Ghetto Regeln", id: "1.10", text: "Gangmitglieder dürfen im HQ jeden töten, wenn die Forderungen nicht erfüllt werden.", penalty: "Keine Angabe" },
  { section: "Ghetto Regeln", id: "1.11", text: "Es ist verboten, Personen zu Animationen zu zwingen (Ausnahmen: Hände hoch oder auf die Knie gehen (bei Polizisten)).", penalty: "Warn" },
  { section: "Ghetto Regeln", id: "1.12", text: "Wenn eine Person den Forderungen nachkommt, darf man diese nicht töten.", penalty: "Jail 120 Minuten" },
  { section: "Ghetto Regeln", id: "1.13", text: "Leader oder Co-Leader müssen den Zeitpunkt für den Überfall auf das Fort Zancudo innerhalb von 1-2 Stunden vor Beginn ankündigen.", penalty: "Warn" },
  { section: "Ghetto Regeln", id: "1.14", text: "Jeder Überfall auf das Fort Zancudo unterliegt einem Cooldown von 2 Stunden.", penalty: "Warn" },
  { section: "Ghetto Regeln", id: "1.15", text: "Gangs, Familien (inkl. inoffizielle Organisationen) dürfen nach einem gerade beendeten Event keine Geiseln nehmen oder Personen ausrauben.", penalty: "Keine Angabe" },

  // Turf Regeln
  { section: "Turf Regeln", id: "2.1", text: "Die Eroberung eines Gebiets ist eine OOC-Situation. Beamten ist es verboten, die Eroberung zu unterbrechen.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.2", text: "Nur Gangmitgliedern können an den Eroberungen teilnehmen.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.3", text: "Die Eroberung ist nur am Montag, Mittwoch, Freitag und Sonntag erlaubt.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.4", text: "Die Eroberung ist von 16:00 Uhr - 23:05 Uhr erlaubt.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.5", text: "4 Angriffe und 4 Verteidigungen sind pro Tag für eine Gang erlaubt.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.6", text: "Removed.", penalty: "Keine Angabe", deleted: true },
  { section: "Turf Regeln", id: "2.7", text: "Nach der Eroberung ist für beide Gangs 25 Minuten lang Pause (andere Gangs dürfen 25 Minuten lang nicht angreifen).", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.8", text: "Es ist verboten, Gebiete ohne Leader anzugreifen.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.9", text: "Bei Teilnahme am Fort-Zancudo-Überfall: 20 Minuten vor dem Überfall, während des Überfalls und 10 Minuten nach dem Überfall keine Gebietsangriffe.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.10", text: "Die Mindestanzahl der Teilnehmer beträgt 5 Personen.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.11", text: "Die Maximalanzahl der Teilnehmer beträgt 10 Personen.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.12", text: "Es ist verboten, die Discord Nachricht zu bearbeiten.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.13", text: "Die Verteidigungsseite muss die Bedingung der Angriffsseite akzeptieren.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.14", text: "Die Gangs müssen in kompletter Spieleranzahl gleichzeitig das Gebiet betreten.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.15", text: "Alle Spieler die nicht an der Eroberung teilnehmen, dürfen nicht in das Gebiet.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.16", text: "Während der Eroberung und 10 Minuten vorher hat der Spieler der Eroberung Immunität und darf nicht getötet werden.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.17", text: "Gangmitglieder dürfen ihre Gang nicht für eine Eroberung wechseln um danach wieder zur ersten Gang zu gehen (Twinks zählen auch).", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.18", text: "Es ist verboten, sich zu heilen und zu looten während der Schießerei.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.19", text: "Es ist verboten eine Weste zu tragen.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.20", text: "Während der Eroberung ist es verboten ein Dach zu betreten. Die Schießerei muss auf dem Boden stattfinden.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.21", text: "Es ist verboten, während der Eroberung bemalte Waffen zu benutzen.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.22", text: "Es ist verboten, Drogen zu nehmen.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.23", text: "Jedes Mitglied muss ein POV für 48 Stunden behalten.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.24", text: "Es ist verboten, externe Software wie VPN zu nutzen.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.25", text: "Wenn ein Mitglied der Eroberung wegen Betrug gebannt wurde, werden alle Gebiete wo das Mitglied teilgenommen hat an die gegnerische Gang übertragen.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.26", text: "Wenn ein Mitglied bewusstlos ist, ist es verboten ihn wiederzubeleben.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.27", text: "Die Verteidigung muss die Eroberung spätestens 2 Minuten vor Ende beitreten.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.28", text: "Die angreifende Gang muss die Art der Waffe und die Anzahl der Teilnehmer festlegen (z.B. 10 gegen 10 - Waffe: Revolver).", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.29", text: "Es ist verboten, Gebäude zu betreten.", penalty: "Jail 120 Minuten" },
  { section: "Turf Regeln", id: "2.30", text: "Es ist verboten, die Ankündigungsnachricht der Eroberung im Discord zu löschen.", penalty: "Mündlicher Warn" },
  { section: "Turf Regeln", id: "2.31", text: "Es ist verboten, das Gebiet zu verlassen. Es ist erlaubt, das Gebiet maximal 7 Sekunden zu verlassen, um ein Hindernis zu umgehen.", penalty: "Jail 120 Minuten" },
  { section: "Turf Regeln", id: "2.32", text: "Ab 5 Minuten vor der Eroberung gilt jedes Mitglied als OOC-Spieler und die Teilnehmer sollten sich im HQ aufhalten.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.33", text: "Wenn eine POV verlangt wird, hast du 24 Stunden Zeit, das Video bereitzustellen.", penalty: "Bann 7 Tage + Verwarnung Leader + Rückgabe des Gebiets" },
  { section: "Turf Regeln", id: "2.34", text: "Es ist verboten, mit dem Auto in das Gebiet zu fahren.", penalty: "Verwarnung Leader + Abbruch Turf" },
  { section: "Turf Regeln", id: "2.35", text: "Gelöschte Regel.", penalty: "Keine Angabe", deleted: true },
  { section: "Turf Regeln", id: "2.36", text: "Alle POV-Anfragen müssen auf Youtube oder Streamable hochgeladen werden.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.37", text: "Gelöschte Regel.", penalty: "Keine Angabe", deleted: true },
  { section: "Turf Regeln", id: "2.38", text: "Du kannst an jedem Eroberungstag maximal 3 Gebiete verkaufen/kaufen.", penalty: "Keine Angabe" },
  { section: "Turf Regeln", id: "2.39", text: "Das ausnutzen von “Rightpeeks” ist verboten (Handwechsel der Waffe während der Deckung hinter der Wand).", penalty: "Bann 7 Tage" },
  { section: "Turf Regeln", id: "2.40", text: "Säfte sind im Gebiet verboten.", penalty: "Bann 1-7 Tage" },
  { section: "Turf Regeln", id: "2.41", text: "Es ist verboten, die Gang zu wechseln, um an einem Turf teilzunehmen (Twink-Accounts zählen auch).", penalty: "Keine Angabe" },

  // Greenzone-Regeln
  { section: "Greenzone Regeln", id: "1.1", text: "Das Töten in einer Greenzone ist verboten.", penalty: "Warn" },
  { section: "Greenzone Regeln", id: "1.2", text: "Das Verkaufen und Kaufen von Waffen und Drogen ist verboten. Personen zu entführen, auszurauben und/oder den Spielern Säcke auf den Kopf zu setzen ist verboten.", penalty: "Warn" },
  { section: "Greenzone Regeln", id: "1.3", text: "Es ist verboten, eine RP-Situation zu verlassen, indem man in eine Greenzone flüchtet.", penalty: "Warn" },

  // Wahl-Regeln
  { section: "Wahl Regeln", id: "1", text: "Jeder kann eine Partei gründen, um an den Wahlen teilzunehmen.", penalty: "Keine Angabe" },
  { section: "Wahl Regeln", id: "2", text: "Der Vorsitzende einer Partei wird zum neuen Gouverneur ernannt.", penalty: "Keine Angabe" },
  { section: "Wahl Regeln", id: "3", text: "Die Partei muss aus mindestens 20 Mitgliedern bestehen; diese müssen einzigartig sein.", penalty: "Keine Angabe" },
  { section: "Wahl Regeln", id: "4", text: "Jede Partei muss ein Wahlprogramm haben, welches den Regeln des Servers entsprechen muss.", penalty: "Keine Angabe" },
  { section: "Wahl Regeln", id: "5", text: "Die Wahl ist ein kompletter IC Prozess. Die Verwendung von OOC ist verboten. Ausnahme ist der offizielle Discord Kanal (#partei-ankündigungen).", penalty: "Keine Angabe" },
  { section: "Wahl Regeln", id: "6", text: "Man darf keine Wahlwerbung im Staatsfunk/Welle, Department Funk/Chat oder in jeglichem weiteren Funk/Radio betreiben.", penalty: "-20 Stimmen" },
  { section: "Wahl Regeln", id: "7", text: "Es darf keine Werbung für deine Partei im Funk für Berufe gemacht werden (LKW, Taxifahrer etc.).", penalty: "-10 Stimmen" },
  { section: "Wahl Regeln", id: "8", text: "Am Tag vor den Wahlen finden Debatten statt, an denen alle Kandidaten teilnehmen müssen. Kandidaten ohne Teilnahme werden ausgeschlossen.", penalty: "Ausschluss von den Wahlen" },
  { section: "Wahl Regeln", id: "9", text: "Bei den Debatten hat jeder Kandidat 10 Minuten Zeit für seine erste Rede, um sein Wahlprogramm vorzustellen.", penalty: "Keine Angabe" },
  { section: "Wahl Regeln", id: "10", text: "Jeder Kandidat kann bis zu 5 Fragen an seinen Gegner stellen.", penalty: "Keine Angabe" },
  { section: "Wahl Regeln", id: "11", text: "Jeder Kandidat kann 5 Fragen von Bürgern erhalten.", penalty: "Keine Angabe" },
  { section: "Wahl Regeln", id: "12", text: "Ein Parteivorsitzender der Partei muss eine saubere Akte haben (keinen aktiven Warn).", penalty: "Keine Angabe" },
  { section: "Wahl Regeln", id: "13", text: "Nachdem die Bewerbung für eine Partei angenommen wurde, findet ein Gespräch mit den zuständigen Berater statt.", penalty: "Keine Angabe" },
  { section: "Wahl Regeln", id: "14", text: "Am Tag nach den Debatten starten die Wahlen.", penalty: "Keine Angabe" },
  { section: "Wahl Regeln", id: "15", text: "Du darfst für deine Partei mit eigen erstellten Events Werbung machen; diese müssen aber über Lifeinvader beworben werden.", penalty: "Keine Angabe" },
  { section: "Wahl Regeln", id: "16", text: "Es ist verboten, bei den Wahlen Versprechungen zu machen, die gegen die Serverregeln verstoßen.", penalty: "Keine Angabe" },
];
